import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#eef3f8', padding: 10 },
  window: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#d4dde8',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    overflow: 'hidden',
    minHeight: 680,
  },
  workspaceHeader: {
    minHeight: 54,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#d8e1ed',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    gap: 12,
  },
  workspaceEyebrow: {
    color: '#2563eb',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  workspaceTitle: { color: '#0f172a', fontSize: 18, fontWeight: '900' },
  workspaceMeta: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  zoomBadge: {
    color: '#315170',
    fontSize: 11,
    fontWeight: '800',
    borderWidth: 1,
    borderColor: '#cbd8e7',
    backgroundColor: '#f6f9fd',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  logoutButton: {
    minHeight: 30,
    borderRadius: 6,
    backgroundColor: '#f1f6fb',
    borderWidth: 1,
    borderColor: '#cbd8e7',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  logoutButtonText: { color: '#123556', fontSize: 12, fontWeight: '800' },
  toolbar: {
    minHeight: 42,
    backgroundColor: '#f7fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#d8e1ed',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 8,
    flexWrap: 'wrap',
  },
  toolbarButton: {
    minHeight: 30,
    borderWidth: 1,
    borderColor: '#bdd2e8',
    backgroundColor: '#ffffff',
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 13,
  },
  toolbarButtonText: { color: '#17466d', fontSize: 11, fontWeight: '800' },
  zoomViewport: { flex: 1, overflow: 'hidden', backgroundColor: '#f8fbff' },
  zoomContent: { flex: 1 },
  mainLayout: { flex: 1, flexDirection: 'row', minHeight: 0 },
  mainLayoutNarrow: { flexDirection: 'column' },
  tablePane: { flex: 1, minWidth: 0, borderRightWidth: 1, borderRightColor: '#d8e1ed' },
  statusStrip: {
    minHeight: 50,
    backgroundColor: '#edf5fd',
    borderBottomWidth: 1,
    borderBottomColor: '#d8e1ed',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 8,
  },
  lifePanel: {
    width: 126,
    borderWidth: 1,
    borderColor: '#c6d8ea',
    backgroundColor: '#ffffff',
    borderRadius: 7,
    padding: 5,
  },
  lifeLabel: { color: '#42627f', fontSize: 10, fontWeight: '800', marginBottom: 3 },
  lifeControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  lifeButton: {
    width: 23,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f8fd',
    borderWidth: 1,
    borderColor: '#b7cde4',
    borderRadius: 4,
  },
  lifeButtonText: { fontWeight: '900', color: '#17466d' },
  lifeValue: { color: '#0f172a', fontSize: 23, lineHeight: 26, fontWeight: '900' },
  phaseStrip: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 5 },
  phaseButton: {
    minWidth: 64,
    minHeight: 24,
    borderWidth: 1,
    borderColor: '#bfd3e8',
    backgroundColor: '#ffffff',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  phaseButtonActive: { backgroundColor: '#2563eb', borderColor: '#2563eb' },
  phaseButtonText: { color: '#35536d', fontSize: 10, fontWeight: '800' },
  phaseButtonTextActive: { color: '#ffffff' },
  battlefield: { flex: 1, backgroundColor: '#f8fbff' },
  battlefieldContent: { minHeight: 460 },
  tableZones: { flex: 1, flexDirection: 'row', padding: 8, gap: 8 },
  sideZone: { width: 104, gap: 8 },
  zoneStack: {
    borderWidth: 1,
    borderColor: '#c0d6ec',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 7,
    minHeight: 132,
  },
  zoneCardBack: {
    height: 64,
    borderRadius: 7,
    backgroundColor: '#3b271b',
    borderWidth: 2,
    borderColor: '#a8845d',
    padding: 6,
    marginBottom: 7,
  },
  zoneCardInner: {
    flex: 1,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#dac1a2',
    backgroundColor: '#765031',
  },
  zoneLabel: { color: '#244967', fontSize: 10, fontWeight: '800' },
  zoneCount: { color: '#0f172a', fontSize: 20, fontWeight: '900', marginTop: 1 },
  zoneSubtitle: { color: '#4f7da8', fontSize: 9, marginTop: 1 },
  boardZone: { flex: 1, gap: 7 },
  battlefieldRow: {
    flex: 1,
    minHeight: 178,
    borderWidth: 1,
    borderColor: '#bfdbf7',
    backgroundColor: '#eef7ff',
    borderRadius: 8,
    padding: 8,
  },
  rowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  rowTitle: { color: '#0f3554', fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  rowMeta: { color: '#4b79a2', fontSize: 10 },
  cardGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, alignItems: 'flex-start' },
  boardCardSlot: { width: 104, gap: 4 },
  centerDivider: {
    minHeight: 26,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#bed8f2',
    backgroundColor: '#e4f2ff',
    borderRadius: 7,
  },
  centerDividerText: { color: '#23547d', fontSize: 10, fontWeight: '800' },
  card: {
    width: 96,
    height: 136,
    borderWidth: 2,
    borderColor: '#0f172a',
    borderRadius: 6,
    padding: 4,
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
  },
  cardCompact: { width: 88, height: 124 },
  cardSelected: { borderColor: '#e0f2fe', shadowColor: '#38bdf8', shadowOpacity: 0.9 },
  cardTapped: { opacity: 0.64, transform: [{ rotate: '8deg' }] },
  cardHeader: { minHeight: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 4 },
  cardName: { flex: 1, fontSize: 8, fontWeight: '900' },
  cardCost: {
    width: 15,
    height: 15,
    borderRadius: 8,
    textAlign: 'center',
    lineHeight: 15,
    backgroundColor: 'rgba(255,255,255,0.6)',
    fontSize: 8,
    fontWeight: '900',
  },
  cardArt: {
    width: '100%',
    height: 45,
    borderWidth: 1,
    borderColor: '#1f2933',
    backgroundColor: '#111827',
    marginTop: 3,
  },
  cardTextBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.36)',
    marginTop: 4,
    padding: 4,
  },
  cardType: { fontSize: 7, fontWeight: '900', marginBottom: 3 },
  cardRules: { fontSize: 7, lineHeight: 9 },
  cardStats: { position: 'absolute', right: 4, bottom: 3, fontSize: 8, fontWeight: '900' },
  slotActions: { flexDirection: 'row', gap: 4 },
  slotButton: {
    flex: 1,
    minHeight: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2d5d8d',
    backgroundColor: '#ffffff',
    borderRadius: 4,
  },
  slotButtonText: { color: '#17466d', fontSize: 8, fontWeight: '800' },
  handPanel: {
    minHeight: 164,
    backgroundColor: '#f4f9ff',
    borderTopWidth: 1,
    borderTopColor: '#d8e9fa',
    padding: 8,
  },
  handHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, gap: 12 },
  handTitle: { color: '#0f3554', fontSize: 12, fontWeight: '900' },
  handHint: { color: '#4f7da8', fontSize: 10 },
  handScroll: { flexGrow: 0 },
  handCardWrap: { width: 94, marginRight: 9, gap: 4 },
  sidePane: { width: 300, backgroundColor: '#ffffff', padding: 10, gap: 10 },
  sidePaneNarrow: { width: '100%', minHeight: 580 },
  previewTabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#d8e1ed' },
  previewTab: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    color: '#45657f',
    fontSize: 10,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: '#d8e1ed',
    backgroundColor: '#f4f7fb',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  previewTabActive: { backgroundColor: '#ffffff', color: '#0f3554', fontWeight: '900' },
  previewCard: { alignItems: 'center', backgroundColor: '#f8fbff', borderWidth: 1, borderColor: '#d8e1ed', borderRadius: 8, padding: 10, gap: 8 },
  previewName: { alignSelf: 'stretch', color: '#0f172a', fontSize: 16, fontWeight: '900' },
  previewType: { alignSelf: 'stretch', color: '#23547d', fontSize: 11, fontWeight: '800' },
  previewText: { alignSelf: 'stretch', color: '#334155', fontSize: 11, lineHeight: 16 },
  previewMetaGrid: { alignSelf: 'stretch', gap: 4, paddingTop: 6, borderTopWidth: 1, borderTopColor: '#d8e1ed' },
  previewMeta: { color: '#5a6f83', fontSize: 10, fontWeight: '700' },
  logPanel: {
    flex: 1,
    minHeight: 220,
    backgroundColor: '#f8fbff',
    borderWidth: 1,
    borderColor: '#d8e1ed',
    borderRadius: 8,
    padding: 8,
  },
  logTitle: { color: '#0f3554', fontSize: 11, fontWeight: '900', marginBottom: 6 },
  logScroll: { flex: 1 },
  logEntry: { color: '#3e5d77', fontSize: 10, lineHeight: 15, marginBottom: 3 },
  footer: {
    minHeight: 26,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#d8e1ed',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    gap: 12,
  },
  footerText: { color: '#5a6f83', fontSize: 10 },
});
