import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#7e8797', padding: 10 },
  window: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#173f8f',
    backgroundColor: '#d8d3bf',
    minHeight: 720,
  },
  titleBar: {
    minHeight: 34,
    backgroundColor: '#0a5ccd',
    borderBottomWidth: 1,
    borderBottomColor: '#04367b',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 10,
  },
  titleText: { color: '#ffffff', fontSize: 14, fontWeight: '700' },
  windowControls: { flexDirection: 'row', alignItems: 'center', height: '100%' },
  windowControl: {
    color: '#ffffff',
    fontSize: 13,
    minWidth: 30,
    textAlign: 'center',
    paddingVertical: 7,
    borderLeftWidth: 1,
    borderLeftColor: '#87b8ff',
  },
  closeControl: {
    minWidth: 34,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#c2362f',
  },
  closeControlText: { color: '#ffffff', fontWeight: '800' },
  menuBar: {
    minHeight: 28,
    backgroundColor: '#eee8d8',
    borderBottomWidth: 1,
    borderBottomColor: '#b8af9b',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    gap: 18,
  },
  menuItem: { color: '#1f2933', fontSize: 13 },
  toolbar: {
    minHeight: 42,
    backgroundColor: '#c9c2ae',
    borderBottomWidth: 1,
    borderBottomColor: '#928871',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    gap: 8,
    flexWrap: 'wrap',
  },
  toolbarButton: {
    minHeight: 28,
    borderWidth: 1,
    borderColor: '#7c755f',
    backgroundColor: '#eee9da',
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  toolbarButtonText: { color: '#1f2933', fontSize: 12, fontWeight: '700' },
  mainLayout: { flex: 1, flexDirection: 'row', minHeight: 0 },
  mainLayoutNarrow: { flexDirection: 'column' },
  tablePane: { flex: 1, minWidth: 0, borderRightWidth: 1, borderRightColor: '#7b7562' },
  statusStrip: {
    minHeight: 58,
    backgroundColor: '#b9b098',
    borderBottomWidth: 1,
    borderBottomColor: '#7b7562',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    gap: 10,
  },
  lifePanel: {
    width: 138,
    borderWidth: 1,
    borderColor: '#756d59',
    backgroundColor: '#e5deca',
    padding: 6,
  },
  lifeLabel: { color: '#26313d', fontSize: 11, fontWeight: '800', marginBottom: 4 },
  lifeControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  lifeButton: {
    width: 26,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8f4e8',
    borderWidth: 1,
    borderColor: '#918873',
  },
  lifeButtonText: { fontWeight: '900', color: '#14213d' },
  lifeValue: { color: '#0f172a', fontSize: 24, lineHeight: 28, fontWeight: '900' },
  phaseStrip: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 5 },
  phaseButton: {
    minWidth: 70,
    minHeight: 26,
    borderWidth: 1,
    borderColor: '#756d59',
    backgroundColor: '#ece5d3',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 7,
  },
  phaseButtonActive: { backgroundColor: '#0f4aa2', borderColor: '#0b3472' },
  phaseButtonText: { color: '#293443', fontSize: 11, fontWeight: '800' },
  phaseButtonTextActive: { color: '#ffffff' },
  battlefield: { flex: 1, backgroundColor: '#12264b' },
  battlefieldContent: { minHeight: 520 },
  tableZones: { flex: 1, flexDirection: 'row', padding: 8, gap: 8 },
  sideZone: { width: 116, gap: 10 },
  zoneStack: {
    borderWidth: 1,
    borderColor: '#69a0d7',
    backgroundColor: '#0c1a34',
    padding: 7,
    minHeight: 148,
  },
  zoneCardBack: {
    height: 78,
    borderRadius: 5,
    backgroundColor: '#3c2519',
    borderWidth: 2,
    borderColor: '#b58d5d',
    padding: 7,
    marginBottom: 8,
  },
  zoneCardInner: {
    flex: 1,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#dac1a2',
    backgroundColor: '#765031',
  },
  zoneLabel: { color: '#e5edf7', fontSize: 11, fontWeight: '800' },
  zoneCount: { color: '#ffffff', fontSize: 22, fontWeight: '900', marginTop: 2 },
  zoneSubtitle: { color: '#9fc1e6', fontSize: 10, marginTop: 2 },
  boardZone: { flex: 1, gap: 8 },
  battlefieldRow: {
    flex: 1,
    minHeight: 210,
    borderWidth: 1,
    borderColor: '#326da8',
    backgroundColor: '#081d3d',
    padding: 8,
  },
  rowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  rowTitle: { color: '#f8fafc', fontSize: 13, fontWeight: '900', textTransform: 'uppercase' },
  rowMeta: { color: '#9fc1e6', fontSize: 11 },
  cardGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, alignItems: 'flex-start' },
  boardCardSlot: { width: 132, gap: 5 },
  centerDivider: {
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#3a78b8',
    backgroundColor: '#0d2e5c',
  },
  centerDividerText: { color: '#c8def7', fontSize: 12, fontWeight: '800' },
  card: {
    width: 124,
    height: 174,
    borderWidth: 2,
    borderColor: '#1f2933',
    borderRadius: 6,
    padding: 5,
    shadowColor: '#000000',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  cardCompact: { width: 104, height: 146 },
  cardSelected: { borderColor: '#f8fafc', shadowColor: '#facc15', shadowOpacity: 0.95 },
  cardTapped: { opacity: 0.64, transform: [{ rotate: '8deg' }] },
  cardHeader: { minHeight: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 4 },
  cardName: { flex: 1, fontSize: 10, fontWeight: '900' },
  cardCost: {
    width: 18,
    height: 18,
    borderRadius: 9,
    textAlign: 'center',
    lineHeight: 18,
    backgroundColor: 'rgba(255,255,255,0.6)',
    fontSize: 10,
    fontWeight: '900',
  },
  cardArt: {
    width: '100%',
    height: 62,
    borderWidth: 1,
    borderColor: '#1f2933',
    backgroundColor: '#111827',
    marginTop: 4,
  },
  cardTextBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.36)',
    marginTop: 5,
    padding: 5,
  },
  cardType: { fontSize: 9, fontWeight: '900', marginBottom: 4 },
  cardRules: { fontSize: 8, lineHeight: 11 },
  cardStats: { position: 'absolute', right: 4, bottom: 3, fontSize: 10, fontWeight: '900' },
  slotActions: { flexDirection: 'row', gap: 5 },
  slotButton: {
    flex: 1,
    minHeight: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#7095bd',
    backgroundColor: '#d8e8f8',
    borderRadius: 3,
  },
  slotButtonText: { color: '#102a43', fontSize: 10, fontWeight: '800' },
  handPanel: {
    minHeight: 204,
    backgroundColor: '#0c1a34',
    borderTopWidth: 1,
    borderTopColor: '#326da8',
    padding: 8,
  },
  handHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, gap: 12 },
  handTitle: { color: '#ffffff', fontSize: 13, fontWeight: '900' },
  handHint: { color: '#9fc1e6', fontSize: 11 },
  handScroll: { flexGrow: 0 },
  handCardWrap: { width: 112, marginRight: 10, gap: 5 },
  sidePane: { width: 318, backgroundColor: '#dcd5c2', padding: 8, gap: 8 },
  sidePaneNarrow: { width: '100%', minHeight: 580 },
  previewTabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#8e856d' },
  previewTab: {
    paddingHorizontal: 9,
    paddingVertical: 7,
    color: '#253142',
    fontSize: 11,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: '#9d9279',
    backgroundColor: '#cfc7b2',
  },
  previewTabActive: { backgroundColor: '#f4eedf', fontWeight: '900' },
  previewCard: { alignItems: 'center', backgroundColor: '#eee8d8', borderWidth: 1, borderColor: '#9d9279', padding: 10, gap: 8 },
  previewName: { alignSelf: 'stretch', color: '#172033', fontSize: 18, fontWeight: '900' },
  previewType: { alignSelf: 'stretch', color: '#334155', fontSize: 12, fontWeight: '800' },
  previewText: { alignSelf: 'stretch', color: '#26313d', fontSize: 12, lineHeight: 18 },
  previewMetaGrid: { alignSelf: 'stretch', gap: 4, paddingTop: 6, borderTopWidth: 1, borderTopColor: '#c4b89a' },
  previewMeta: { color: '#475569', fontSize: 11, fontWeight: '700' },
  logPanel: {
    flex: 1,
    minHeight: 220,
    backgroundColor: '#0d2446',
    borderWidth: 1,
    borderColor: '#6f96c1',
    padding: 8,
  },
  logTitle: { color: '#dbeafe', fontSize: 12, fontWeight: '900', marginBottom: 6 },
  logScroll: { flex: 1 },
  logEntry: { color: '#c7d9ee', fontSize: 11, lineHeight: 16, marginBottom: 3 },
  footer: {
    minHeight: 28,
    backgroundColor: '#eee8d8',
    borderTopWidth: 1,
    borderTopColor: '#928871',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    gap: 12,
  },
  footerText: { color: '#334155', fontSize: 11 },
});
